name: Runner maintenance

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Sets a schedule for executing the jobs
  schedule:
    - cron: "10 7 * * 2,5"
permissions:
  id-token: write
  contents: read

jobs:

  macos-maintenance:
    # Sets a matrix of labels on which to run the scripts
    strategy:
      matrix:
        runner:
          - mac-1
          - mac-2
          - mac-3
          - mac-4
    # The job will run in parallel for each of the runner labels listed above
    runs-on: ${{ matrix.runner }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      # Runs a set of commands using the runners shell
      - name: Cleanup docker and upgrade brew
        env:
          HOMEBREW_NO_ASK: 1
        run: |
          docker system prune -fa
          brew upgrade -y
          brew cleanup

